### PR TITLE
added GitHub action to build and update cmake files to use find_package 

### PR DESCRIPTION
**Pull request by gittiver**

### CODE REVIEW

**Comment by dvertx** [comment]
Thank you for the interest and pull requests. Haven't had time to really read and test your commits, yet all seems OK at first glance. Will merge soon

**Comment by gittiver** [comment]
you are welcome, maybe we can bundle the efforts in the forks in an organization where we are part of. 
README.md was also created in another fork and PR - I realized that too late. 

some fixes for warnings will also follow in separate PR. 

doxygen generated stuff can also used for github webpage - i did this here : https://github.com/OpenCoin/opencoin-issuer-cpp / 
 see link on right side, the content is updated automatically on push to main branch.

**Comment by dvertx** [comment]
> you are welcome, maybe we can bundle the efforts in the forks in an organization where we are part of. 

That is a nice idea, if you think wxShapeFramework would and should evolve/improve for the better. Alas, I'm not the original author, and intended this repo for personal use when created, while considering its usefulness for others. I believe @MichalBliznak (https://github.com/MichalBliznak) should be contacted to see if he might be interested.
 
> doxygen generated stuff can also used for github webpage - i did this here : https://github.com/OpenCoin/opencoin-issuer-cpp / see link on right side, the content is updated automatically on push to main branch.

Yes, this would be valuable for an organized fork

**Comment by gittiver** [comment]
I tried to create an organization, see wxShapers. you and Michael are already invited.

**Comment by dvertx** [comment]
Thanks, I have joined the wxShaper organization

**Comment by dvertx** [comment]
I need  access rights to push into wxShaper main repo

**Comment by gittiver** [comment]
> I need access rights to push into wxShaper main repo

You now have.

**Pull request closed without merging**
